objects_create:
  defaults: { _controller: PressEnterMatematiconBundle:Objects:create }
  pattern: /
  methods: POST

objects_save:
  defaults: { _controller: PressEnterMatematiconBundle:Objects:save }
  pattern: /save
  methods: POST

objects_get:
  defaults: { _controller: PressEnterMatematiconBundle:Objects:get }
  pattern: /{item}
  methods: GET

objects_list:
  defaults: { _controller: PressEnterMatematiconBundle:Objects:list }
  pattern: /
  methods: GET

objects_delete:
  defaults: { _controller: PressEnterMatematiconBundle:Objects:delete }
  pattern: /{item}
  methods: DELETE

objects_image:
  defaults: { _controller: PressEnterMatematiconBundle:Objects:image }
  pattern: /{item}/image
  methods: GET

