press_enter_matematicon_homepage:
    path:     /
    defaults: { _controller: PressEnterMatematiconBundle:Default:index }

my_objects:
    resource: "routing/objects.yml"
    prefix: /my_objects

city:
    resource: "routing/city.yml"
    prefix: /city

denuncia:
    resource: "routing/denuncia.yml"
    prefix: /denuncia


