PressEnter\MatematiconBundle\Entity\Scene:
    type:  entity
    table: scene
    id:
        id:
            type: integer
            generator:
                strategy: AUTO
    fields:
        title:
            type: string
            length: 50
