fos_user_security:
    resource: "@FOSUserBundle/Resources/config/routing/security.xml"

press_enter_matematicon:
    resource: "@PressEnterMatematiconBundle/Resources/config/routing.yml"
    prefix:   /

